version: '3'

services:
  web:
    image: ${image}:${env.BUILD_ID}
    container_name: web
    restart: always
    ports:
      - '8060:8060'
    environment:
      - NAME_WEB=web
      - PORT=8060
    network_mode: "host"
